[package]
name = "eleven"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent.workspace = true
combine.workspace = true
derive_more.workspace = true
parse.workspace = true
strum.workspace = true